// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PropFlow.Infrastructure.Autopilot;

#nullable disable

namespace PropFlow.Infrastructure.Persistence.Migrations.Autopilot
{
    [DbContext(typeof(AutopilotStore))]
    [Migration("20260914185445_ActionsAndRecommendations")]
    partial class ActionsAndRecommendations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("autopilot")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PropFlow.Domain.Autopilot.AutopilotActionProposal", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ConcurrencyToken")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DecidedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DecisionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExecutionOutcome")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PayloadFieldsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PayloadSummary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PreviewChangesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PreviewDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("ProposedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProposedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecommendationId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequiredApprovalCapability")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RequiredConsentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RequiredExecutionCapability")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "RecommendationId", "Status");

                    b.ToTable("ActionProposals", "autopilot");
                });

            modelBuilder.Entity("PropFlow.Domain.Autopilot.AutopilotAuditEntry", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "SubjectType", "SubjectId", "OccurredAt");

                    b.ToTable("AuditEntries", "autopilot");
                });

            modelBuilder.Entity("PropFlow.Domain.Autopilot.AutopilotEvidence", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<Guid>("FindingId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FreshnessAsOf")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImpactCategory")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ImpactDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("ImpactEstimatedAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("InputsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SourceLinksJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "FindingId")
                        .IsUnique();

                    b.ToTable("Evidence", "autopilot");
                });

            modelBuilder.Entity("PropFlow.Domain.Autopilot.AutopilotFeedback", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("FindingId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecordedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Sentiment")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "FindingId", "RecordedBy", "RecordedAt");

                    b.ToTable("Feedback", "autopilot");
                });

            modelBuilder.Entity("PropFlow.Domain.Autopilot.AutopilotFinding", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DismissedReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("FreshnessAsOf")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PortfolioId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("SignalType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("SnoozedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "RunId");

                    b.HasIndex("OrganizationId", "SignalType");

                    b.HasIndex("OrganizationId", "PortfolioId", "Status");

                    b.HasIndex("OrganizationId", "PropertyId", "Status");

                    b.HasIndex("OrganizationId", "Status", "Severity", "DetectedAt");

                    b.ToTable("Findings", "autopilot");
                });

            modelBuilder.Entity("PropFlow.Domain.Autopilot.AutopilotFindingRead", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FindingId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ViewerId")
                        .HasColumnType("uuid");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "FindingId", "ViewerId")
                        .IsUnique();

                    b.ToTable("FindingReads", "autopilot");
                });

            modelBuilder.Entity("PropFlow.Domain.Autopilot.AutopilotRecommendation", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DecidedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DecisionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("FindingId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ProposedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProposedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "FindingId", "Status");

                    b.ToTable("Recommendations", "autopilot");
                });

            modelBuilder.Entity("PropFlow.Domain.Autopilot.AutopilotRun", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("FindingCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "StartedAt")
                        .IsDescending(false, true);

                    b.ToTable("Runs", "autopilot");
                });

            modelBuilder.Entity("PropFlow.Domain.Autopilot.AutopilotActionProposal", b =>
                {
                    b.HasOne("PropFlow.Domain.Autopilot.AutopilotRecommendation", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "RecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PropFlow.Domain.Autopilot.AutopilotEvidence", b =>
                {
                    b.HasOne("PropFlow.Domain.Autopilot.AutopilotFinding", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "FindingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PropFlow.Domain.Autopilot.AutopilotFeedback", b =>
                {
                    b.HasOne("PropFlow.Domain.Autopilot.AutopilotFinding", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "FindingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PropFlow.Domain.Autopilot.AutopilotFinding", b =>
                {
                    b.HasOne("PropFlow.Domain.Autopilot.AutopilotRun", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PropFlow.Domain.Autopilot.AutopilotFindingRead", b =>
                {
                    b.HasOne("PropFlow.Domain.Autopilot.AutopilotFinding", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "FindingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PropFlow.Domain.Autopilot.AutopilotRecommendation", b =>
                {
                    b.HasOne("PropFlow.Domain.Autopilot.AutopilotFinding", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "FindingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
